version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7999:7999"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=shop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA=product_service
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: