services:
  product-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7999:7999"
    environment:
      - DB_HOST=localhost  # меняем с 'db' на 'localhost'
      - DB_PORT=5432
      - DB_NAME=shop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA=product_service
    # Убираем depends_on, т.к. БД уже запущена
    volumes:
      - .:/app
    restart: unless-stopped